# Generated by Django 5.2 on 2025-06-08 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('formato', models.CharField(choices=[('2D', '2D - $3.50'), ('3D', '3D - $4.50'), ('IMAX', 'IMAX - $6.00')], max_length=4)),
                ('sala', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('asientos', models.CharField(max_length=255)),
                ('cantidad_boletos', models.PositiveIntegerField(default=1)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('codigo_reserva', models.CharField(max_length=10, unique=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pelicula')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
            },
        ),
    ]
