# Generated by Django 5.2.6 on 2025-09-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
